name: Instalación de Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pruebas-laravel:

    runs-on: ubuntu-latest

    steps:
    - name: Configurar PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - name: Obtener el código fuente
      uses: actions/checkout@v4
    - name: Copiar archivo .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Instalar dependencias de PHP
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generar clave de aplicación
      run: php artisan key:generate
    - name: Establecer permisos de directorios
      run: chmod -R 777 storage bootstrap/cache
    - name: Crear base de datos SQLite
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Instalar dependencias de Node.js
      run: npm install --silent
    - name: Construir activos con Vite
      run: npm run build --silent
    - name: Ejecutar pruebas (Unitarias y de Características) con PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
